---

- name: Installing force-dns
  copy:
    src: force-dns 
    dest: /usr/local/bin/force-dns
    group: root
    owner: root
    mode: 0755

# Update the following with correct IP addresses.
# - name: Configure force-dns
#   shell: /usr/local/bin/force-dns configure 1.2.3.4 5.6.7.8
