---

- name: Install general Linux utilities
  apt:
    pkg:
      - curl
      - emacs
      - git
      - htop
      - mc
      - python3-pip
      - stow
      - tmux
      - tree
      - zsh
      - doublecmd-gtk
      
