---
# 
# Installs linux-workspaces and all necessary tools to customize
# the workspaces settings, like dotfiles.
#

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg

- name: Installing Visual Studio Code
  apt:
    update-cache: yes
    pkg:
      - apt-transport-https
      - code

