---

- name: Installing Docker
  apt:
    pkg:
      - docker.io

- name: Add the developer user to the docker group.
  user:
    name: developer
    shell: /bin/bash
    groups: docker
    append: yes
